name: alarm_matrix_app
description: Alarm Matrix app (Desktop + Android) backed by SQLite
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # SQLite ORM
  drift: ^2.20.0
  sqlite3_flutter_libs: ^0.5.24
  path_provider: ^2.1.4
  path: ^1.9.0

  # State management (легко и быстро)
  flutter_riverpod: ^2.5.1

  # Import Excel + выбор файла
  file_picker: ^8.0.6
  excel: ^4.0.6

  # Utils
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.20.0
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true
